WIP: Add option to write sidecar file with additional metadata
artefactual-labs/mets-retriever pull request #2
Opened 2022-06-15 19:57 UTC by tw4l

2022-06-15 20:40 UTC, tw4l commented
Hi @djjuhasz - a few smallish additions that could use a look when you have a moment. This should be the last development on this for now, pending user feedback. Thanks!

2022-06-15 22:39 UTC, djjuhasz requested changes
Just one requested change @tw4l.

2022-06-15 22:39 UTC, djjuhasz commented on mets_retriever/mets_retriever.py
> +                if not aip.get("replicas"):
I think it's better to combine these two "if" statements into a single "if" with an "and" operator.

2022-06-16 14:34 UTC, tw4l commented on mets_retriever/mets_retriever.py
> +                if not aip.get("replicas"):
yup, that is better!

2022-06-16 14:34 UTC, tw4l commented
@djjuhasz the requested change is made when you're ready to take another look. thanks!

2022-06-16 16:00 UTC, djjuhasz approved these changes
LGTM! 👍

2022-06-16 17:28 UTC, merged